workflows:
  ios-build:
    name: Atalaia IOS

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: br.com.sysrota.atalaia.app

    scripts:
      - name: Ensure iOS platform
        script: |
          cd app
          flutter create --platforms=ios --org br.com.sysrota.atalaia .

      - name: Fix Bundle Identifier
        script: |
          cd app/ios
          sed -i '' 's/com.example.app/br.com.sysrota.atalaia.app/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/com.example.runner/br.com.sysrota.atalaia.app/g' Runner.xcodeproj/project.pbxproj

      - name: Fix iOS deployment target
        script: |
          cd app/ios
          sed -i '' "s/platform :ios, .*/platform :ios, '14.0'/" Podfile
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g" Runner.xcodeproj/project.pbxproj

      - name: Clean project
        script: |
          cd app
          flutter clean

      - name: Install dependencies
        script: |
          cd app
          flutter pub get

      - name: Install Pods
        script: |
          cd app/ios
          pod deintegrate
          pod install

      - name: Build (no codesign)
        script: |
          cd app
          flutter build ipa --release --no-codesign

      - name: Apply Code Signing
        script: |
          xcode-project use-profiles

    artifacts:
      - app/build/ios/ipa/*.ipa